// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: data.proto

package spacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_CONFIRMED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
	BookingStatus_BOOKING_STATUS_COMPLETED   BookingStatus = 4
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_CONFIRMED",
		3: "BOOKING_STATUS_CANCELLED",
		4: "BOOKING_STATUS_COMPLETED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_CONFIRMED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
		"BOOKING_STATUS_COMPLETED":   4,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_data_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Continent     string                 `protobuf:"bytes,4,opt,name=continent,proto3" json:"continent,omitempty"`
	KnownFor      string                 `protobuf:"bytes,5,opt,name=known_for,json=knownFor,proto3" json:"known_for,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *Destination) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Destination) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Destination) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Destination) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

func (x *Destination) GetKnownFor() string {
	if x != nil {
		return x.KnownFor
	}
	return ""
}

func (x *Destination) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Destination) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Activity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LocationName   string                 `protobuf:"bytes,4,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	Duration       float32                `protobuf:"fixed32,5,opt,name=duration,proto3" json:"duration,omitempty"`
	TimeOfDay      string                 `protobuf:"bytes,6,opt,name=time_of_day,json=timeOfDay,proto3" json:"time_of_day,omitempty"`
	FamilyFriendly bool                   `protobuf:"varint,7,opt,name=family_friendly,json=familyFriendly,proto3" json:"family_friendly,omitempty"`
	Price          int32                  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	DestinationRef string                 `protobuf:"bytes,9,opt,name=destination_ref,json=destinationRef,proto3" json:"destination_ref,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *Activity) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *Activity) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Activity) GetTimeOfDay() string {
	if x != nil {
		return x.TimeOfDay
	}
	return ""
}

func (x *Activity) GetFamilyFriendly() bool {
	if x != nil {
		return x.FamilyFriendly
	}
	return false
}

func (x *Activity) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Activity) GetDestinationRef() string {
	if x != nil {
		return x.DestinationRef
	}
	return ""
}

func (x *Activity) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Destination messages
type GetDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDestinationRequest) Reset() {
	*x = GetDestinationRequest{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDestinationRequest) ProtoMessage() {}

func (x *GetDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDestinationRequest.ProtoReflect.Descriptor instead.
func (*GetDestinationRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetDestinationRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ListDestinationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsRequest) Reset() {
	*x = ListDestinationsRequest{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsRequest) ProtoMessage() {}

func (x *ListDestinationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsRequest.ProtoReflect.Descriptor instead.
func (*ListDestinationsRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

type ListDestinationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destinations  []*Destination         `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsResponse) Reset() {
	*x = ListDestinationsResponse{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsResponse) ProtoMessage() {}

func (x *ListDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsResponse.ProtoReflect.Descriptor instead.
func (*ListDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *ListDestinationsResponse) GetDestinations() []*Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type CreateDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *Destination           `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDestinationRequest) Reset() {
	*x = CreateDestinationRequest{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDestinationRequest) ProtoMessage() {}

func (x *CreateDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDestinationRequest.ProtoReflect.Descriptor instead.
func (*CreateDestinationRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDestinationRequest) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

type UpdateDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *Destination           `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDestinationRequest) Reset() {
	*x = UpdateDestinationRequest{}
	mi := &file_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDestinationRequest) ProtoMessage() {}

func (x *UpdateDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDestinationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDestinationRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDestinationRequest) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

type DeleteDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDestinationRequest) Reset() {
	*x = DeleteDestinationRequest{}
	mi := &file_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDestinationRequest) ProtoMessage() {}

func (x *DeleteDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDestinationRequest.ProtoReflect.Descriptor instead.
func (*DeleteDestinationRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDestinationRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Activity messages
type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{8}
}

func (x *GetActivityRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ListActivitiesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DestinationRef string                 `protobuf:"bytes,1,opt,name=destination_ref,json=destinationRef,proto3" json:"destination_ref,omitempty"` // optional filter by destination
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	mi := &file_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{9}
}

func (x *ListActivitiesRequest) GetDestinationRef() string {
	if x != nil {
		return x.DestinationRef
	}
	return ""
}

type ListActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResponse) Reset() {
	*x = ListActivitiesResponse{}
	mi := &file_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResponse) ProtoMessage() {}

func (x *ListActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{10}
}

func (x *ListActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type CreateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *Activity              `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{11}
}

func (x *CreateActivityRequest) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type UpdateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *Activity              `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityRequest) Reset() {
	*x = UpdateActivityRequest{}
	mi := &file_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityRequest) ProtoMessage() {}

func (x *UpdateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateActivityRequest) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type DeleteActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityRequest) Reset() {
	*x = DeleteActivityRequest{}
	mi := &file_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityRequest) ProtoMessage() {}

func (x *DeleteActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityRequest.ProtoReflect.Descriptor instead.
func (*DeleteActivityRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteActivityRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Booking
type BookingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DestinationRef string                 `protobuf:"bytes,1,opt,name=destination_ref,json=destinationRef,proto3" json:"destination_ref,omitempty"`
	ActivityRefs   []string               `protobuf:"bytes,2,rep,name=activity_refs,json=activityRefs,proto3" json:"activity_refs,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserId         string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingRequest) Reset() {
	*x = BookingRequest{}
	mi := &file_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequest) ProtoMessage() {}

func (x *BookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequest.ProtoReflect.Descriptor instead.
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{14}
}

func (x *BookingRequest) GetDestinationRef() string {
	if x != nil {
		return x.DestinationRef
	}
	return ""
}

func (x *BookingRequest) GetActivityRefs() []string {
	if x != nil {
		return x.ActivityRefs
	}
	return nil
}

func (x *BookingRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *BookingRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *BookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status        BookingStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=moon.space.v1.BookingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{15}
}

func (x *BookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingResponse) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{16}
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\rmoon.space.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\vDestination\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1c\n" +
	"\tcontinent\x18\x04 \x01(\tR\tcontinent\x12\x1b\n" +
	"\tknown_for\x18\x05 \x01(\tR\bknownFor\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"\xb8\x02\n" +
	"\bActivity\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rlocation_name\x18\x04 \x01(\tR\flocationName\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x02R\bduration\x12\x1e\n" +
	"\vtime_of_day\x18\x06 \x01(\tR\ttimeOfDay\x12'\n" +
	"\x0ffamily_friendly\x18\a \x01(\bR\x0efamilyFriendly\x12\x14\n" +
	"\x05price\x18\b \x01(\x05R\x05price\x12'\n" +
	"\x0fdestination_ref\x18\t \x01(\tR\x0edestinationRef\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\")\n" +
	"\x15GetDestinationRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\x19\n" +
	"\x17ListDestinationsRequest\"Z\n" +
	"\x18ListDestinationsResponse\x12>\n" +
	"\fdestinations\x18\x01 \x03(\v2\x1a.moon.space.v1.DestinationR\fdestinations\"X\n" +
	"\x18CreateDestinationRequest\x12<\n" +
	"\vdestination\x18\x01 \x01(\v2\x1a.moon.space.v1.DestinationR\vdestination\"X\n" +
	"\x18UpdateDestinationRequest\x12<\n" +
	"\vdestination\x18\x01 \x01(\v2\x1a.moon.space.v1.DestinationR\vdestination\",\n" +
	"\x18DeleteDestinationRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"&\n" +
	"\x12GetActivityRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"@\n" +
	"\x15ListActivitiesRequest\x12'\n" +
	"\x0fdestination_ref\x18\x01 \x01(\tR\x0edestinationRef\"Q\n" +
	"\x16ListActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.moon.space.v1.ActivityR\n" +
	"activities\"L\n" +
	"\x15CreateActivityRequest\x123\n" +
	"\bactivity\x18\x01 \x01(\v2\x17.moon.space.v1.ActivityR\bactivity\"L\n" +
	"\x15UpdateActivityRequest\x123\n" +
	"\bactivity\x18\x01 \x01(\v2\x17.moon.space.v1.ActivityR\bactivity\")\n" +
	"\x15DeleteActivityRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\xe9\x01\n" +
	"\x0eBookingRequest\x12'\n" +
	"\x0fdestination_ref\x18\x01 \x01(\tR\x0edestinationRef\x12#\n" +
	"\ractivity_refs\x18\x02 \x03(\tR\factivityRefs\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"f\n" +
	"\x0fBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.moon.space.v1.BookingStatusR\x06status\"\x0f\n" +
	"\rEmptyResponse*\xa5\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x03\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x042\xb1\b\n" +
	"\rTravelService\x12R\n" +
	"\x0eGetDestination\x12$.moon.space.v1.GetDestinationRequest\x1a\x1a.moon.space.v1.Destination\x12c\n" +
	"\x12SearchDestinations\x12$.moon.space.v1.GetDestinationRequest\x1a'.moon.space.v1.ListDestinationsResponse\x12c\n" +
	"\x10ListDestinations\x12&.moon.space.v1.ListDestinationsRequest\x1a'.moon.space.v1.ListDestinationsResponse\x12X\n" +
	"\x11CreateDestination\x12'.moon.space.v1.CreateDestinationRequest\x1a\x1a.moon.space.v1.Destination\x12X\n" +
	"\x11UpdateDestination\x12'.moon.space.v1.UpdateDestinationRequest\x1a\x1a.moon.space.v1.Destination\x12Z\n" +
	"\x11DeleteDestination\x12'.moon.space.v1.DeleteDestinationRequest\x1a\x1c.moon.space.v1.EmptyResponse\x12I\n" +
	"\vGetActivity\x12!.moon.space.v1.GetActivityRequest\x1a\x17.moon.space.v1.Activity\x12]\n" +
	"\x0eListActivities\x12$.moon.space.v1.ListActivitiesRequest\x1a%.moon.space.v1.ListActivitiesResponse\x12O\n" +
	"\x0eCreateActivity\x12$.moon.space.v1.CreateActivityRequest\x1a\x17.moon.space.v1.Activity\x12O\n" +
	"\x0eUpdateActivity\x12$.moon.space.v1.UpdateActivityRequest\x1a\x17.moon.space.v1.Activity\x12T\n" +
	"\x0eDeleteActivity\x12$.moon.space.v1.DeleteActivityRequest\x1a\x1c.moon.space.v1.EmptyResponse\x12P\n" +
	"\x0fBookDestination\x12\x1d.moon.space.v1.BookingRequest\x1a\x1e.moon.space.v1.BookingResponseB\xa5\x01\n" +
	"\x11com.moon.space.v1B\tDataProtoP\x01Z/github.com/codeharik/moonspace/proto/v1;spacev1\xa2\x02\x03MSX\xaa\x02\rMoon.Space.V1\xca\x02\rMoon\\Space\\V1\xe2\x02\x19Moon\\Space\\V1\\GPBMetadata\xea\x02\x0fMoon::Space::V1b\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_data_proto_goTypes = []any{
	(BookingStatus)(0),               // 0: moon.space.v1.BookingStatus
	(*Destination)(nil),              // 1: moon.space.v1.Destination
	(*Activity)(nil),                 // 2: moon.space.v1.Activity
	(*GetDestinationRequest)(nil),    // 3: moon.space.v1.GetDestinationRequest
	(*ListDestinationsRequest)(nil),  // 4: moon.space.v1.ListDestinationsRequest
	(*ListDestinationsResponse)(nil), // 5: moon.space.v1.ListDestinationsResponse
	(*CreateDestinationRequest)(nil), // 6: moon.space.v1.CreateDestinationRequest
	(*UpdateDestinationRequest)(nil), // 7: moon.space.v1.UpdateDestinationRequest
	(*DeleteDestinationRequest)(nil), // 8: moon.space.v1.DeleteDestinationRequest
	(*GetActivityRequest)(nil),       // 9: moon.space.v1.GetActivityRequest
	(*ListActivitiesRequest)(nil),    // 10: moon.space.v1.ListActivitiesRequest
	(*ListActivitiesResponse)(nil),   // 11: moon.space.v1.ListActivitiesResponse
	(*CreateActivityRequest)(nil),    // 12: moon.space.v1.CreateActivityRequest
	(*UpdateActivityRequest)(nil),    // 13: moon.space.v1.UpdateActivityRequest
	(*DeleteActivityRequest)(nil),    // 14: moon.space.v1.DeleteActivityRequest
	(*BookingRequest)(nil),           // 15: moon.space.v1.BookingRequest
	(*BookingResponse)(nil),          // 16: moon.space.v1.BookingResponse
	(*EmptyResponse)(nil),            // 17: moon.space.v1.EmptyResponse
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
}
var file_data_proto_depIdxs = []int32{
	1,  // 0: moon.space.v1.ListDestinationsResponse.destinations:type_name -> moon.space.v1.Destination
	1,  // 1: moon.space.v1.CreateDestinationRequest.destination:type_name -> moon.space.v1.Destination
	1,  // 2: moon.space.v1.UpdateDestinationRequest.destination:type_name -> moon.space.v1.Destination
	2,  // 3: moon.space.v1.ListActivitiesResponse.activities:type_name -> moon.space.v1.Activity
	2,  // 4: moon.space.v1.CreateActivityRequest.activity:type_name -> moon.space.v1.Activity
	2,  // 5: moon.space.v1.UpdateActivityRequest.activity:type_name -> moon.space.v1.Activity
	18, // 6: moon.space.v1.BookingRequest.start_date:type_name -> google.protobuf.Timestamp
	18, // 7: moon.space.v1.BookingRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 8: moon.space.v1.BookingResponse.status:type_name -> moon.space.v1.BookingStatus
	3,  // 9: moon.space.v1.TravelService.GetDestination:input_type -> moon.space.v1.GetDestinationRequest
	3,  // 10: moon.space.v1.TravelService.SearchDestinations:input_type -> moon.space.v1.GetDestinationRequest
	4,  // 11: moon.space.v1.TravelService.ListDestinations:input_type -> moon.space.v1.ListDestinationsRequest
	6,  // 12: moon.space.v1.TravelService.CreateDestination:input_type -> moon.space.v1.CreateDestinationRequest
	7,  // 13: moon.space.v1.TravelService.UpdateDestination:input_type -> moon.space.v1.UpdateDestinationRequest
	8,  // 14: moon.space.v1.TravelService.DeleteDestination:input_type -> moon.space.v1.DeleteDestinationRequest
	9,  // 15: moon.space.v1.TravelService.GetActivity:input_type -> moon.space.v1.GetActivityRequest
	10, // 16: moon.space.v1.TravelService.ListActivities:input_type -> moon.space.v1.ListActivitiesRequest
	12, // 17: moon.space.v1.TravelService.CreateActivity:input_type -> moon.space.v1.CreateActivityRequest
	13, // 18: moon.space.v1.TravelService.UpdateActivity:input_type -> moon.space.v1.UpdateActivityRequest
	14, // 19: moon.space.v1.TravelService.DeleteActivity:input_type -> moon.space.v1.DeleteActivityRequest
	15, // 20: moon.space.v1.TravelService.BookDestination:input_type -> moon.space.v1.BookingRequest
	1,  // 21: moon.space.v1.TravelService.GetDestination:output_type -> moon.space.v1.Destination
	5,  // 22: moon.space.v1.TravelService.SearchDestinations:output_type -> moon.space.v1.ListDestinationsResponse
	5,  // 23: moon.space.v1.TravelService.ListDestinations:output_type -> moon.space.v1.ListDestinationsResponse
	1,  // 24: moon.space.v1.TravelService.CreateDestination:output_type -> moon.space.v1.Destination
	1,  // 25: moon.space.v1.TravelService.UpdateDestination:output_type -> moon.space.v1.Destination
	17, // 26: moon.space.v1.TravelService.DeleteDestination:output_type -> moon.space.v1.EmptyResponse
	2,  // 27: moon.space.v1.TravelService.GetActivity:output_type -> moon.space.v1.Activity
	11, // 28: moon.space.v1.TravelService.ListActivities:output_type -> moon.space.v1.ListActivitiesResponse
	2,  // 29: moon.space.v1.TravelService.CreateActivity:output_type -> moon.space.v1.Activity
	2,  // 30: moon.space.v1.TravelService.UpdateActivity:output_type -> moon.space.v1.Activity
	17, // 31: moon.space.v1.TravelService.DeleteActivity:output_type -> moon.space.v1.EmptyResponse
	16, // 32: moon.space.v1.TravelService.BookDestination:output_type -> moon.space.v1.BookingResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		EnumInfos:         file_data_proto_enumTypes,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
